In [1]:
# !pip install google-cloud-bigquery==2.34.3

In [2]:
import os
os.getcwd()

'c:\\Users\\bukuw\\work\\automl_edc'

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
# -- setup connection
import gspread
from pydata_google_auth import get_user_credentials
from google.cloud import bigquery

project_id = 'ledger-fcc1e'
creds = get_user_credentials([
    'https://www.googleapis.com/auth/cloud-platform', 
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive',
])
client = bigquery.Client(project=project_id, credentials=creds)

gc = gspread.authorize(creds) 
pull_data = lambda query: client.query(query).result().to_dataframe()
get_worksheet = lambda key, name: gc.open_by_key(key).worksheet(name)

In [5]:
# query =\
# '''
# WITH main AS (
#   SELECT 
#     phone_number_clean,
#     '1' AS responded,
#     interested_to_EDC_flag,
#     ms_area,
#     acquisition_channel,
#     user_age,
#     kyc_tier,
#     loyalty_tier,
#     age_on_core_days,
#     age_on_ncore_days,
#     age_on_accounting_days,
#     referee_count,
#     est_daily_customer,
#     count_trf,
#     edc_count,
#     edc_type,
#     business_age,
#     core_before_shutdown_flag,
#     ppob_before_shutdown_flag,
#     M0_core_count,
#     M0_ppob_payment_count,
#     M0_QRIS_payment_count,
#     LM_core_count,
#     LM_ppob_payment_count,
#     LM_QRIS_payment_count,
#     L2M_core_count,
#     L2M_ppob_payment_count,
#     L2M_QRIS_payment_count,
#     L3M_core_count,
#     L3M_ppob_payment_count,
#     L3M_QRIS_payment_count,
#     M0_corepayment_TPV,
#     M0_ppob_TPV,
#     M0_QRIS_TPV,
#     LM_corepayment_TPV,
#     LM_ppob_TPV,
#     LM_QRIS_TPV,
#     L2M_corepayment_TPV,
#     L2M_ppob_TPV,
#     L2M_QRIS_TPV,
#     L3M_corepayment_TPV,
#     L3M_ppob_TPV,
#     L3M_QRIS_TPV,
#     m0_transaxi_cnt,
#     m0_Utang_cnt,
#     lm_transaxi_cnt,
#     lm_Utang_cnt,
#     m2_transaxi_cnt,
#     m2_Utang_cnt,
#     m3_transaxi_cnt,
#     m3_Utang_cnt,
#   FROM `ledger-fcc1e.dg_buku_trnsfmd.EDC_survey_userbase`

#   UNION ALL

#   SELECT DISTINCT
#     phone_number_clean,
#     responded,
#     '0' AS interested_to_EDC_flag,
#     ms_area,
#     acquisition_channel,
#     user_age,
#     kyc_tier,
#     loyalty_tier,
#     age_on_core_days,
#     age_on_ncore_days,
#     age_on_accounting_days,
#     referee_count,
#     est_daily_customer,
#     count_trf,
#     edc_count,
#     edc_type,
#     business_age,
#     core_before_shutdown_flag,
#     ppob_before_shutdown_flag,
#     M0_core_count,
#     M0_ppob_payment_count,
#     M0_QRIS_payment_count,
#     LM_core_count,
#     LM_ppob_payment_count,
#     LM_QRIS_payment_count,
#     L2M_core_count,
#     L2M_ppob_payment_count,
#     L2M_QRIS_payment_count,
#     L3M_core_count,
#     L3M_ppob_payment_count,
#     L3M_QRIS_payment_count,
#     M0_corepayment_TPV,
#     M0_ppob_TPV,
#     M0_QRIS_TPV,
#     LM_corepayment_TPV,
#     LM_ppob_TPV,
#     LM_QRIS_TPV,
#     L2M_corepayment_TPV,
#     L2M_ppob_TPV,
#     L2M_QRIS_TPV,
#     L3M_corepayment_TPV,
#     L3M_ppob_TPV,
#     L3M_QRIS_TPV,
#     m0_transaxi_cnt,
#     m0_Utang_cnt,
#     lm_transaxi_cnt,
#     lm_Utang_cnt,
#     m2_transaxi_cnt,
#     m2_Utang_cnt,
#     m3_transaxi_cnt,
#     m3_Utang_cnt,
#   FROM `ledger-fcc1e.dg_buku_trnsfmd.EDC_survey_userbase_all`
#   WHERE phone_number_clean IS NOT NULL
# )

# SELECT * EXCEPT(responded, rn)
# FROM (
#   SELECT
#     *,
#     ROW_NUMBER() OVER(PARTITION BY phone_number_clean ORDER BY interested_to_edc_flag DESC) AS rn
#   FROM main
# )
# WHERE rn = 1
# '''

# raw = client.query(query).result().to_dataframe()
# raw.to_pickle('data/raw_data.pkl')

In [6]:
# query =\
# '''
# SELECT *
# FROM `ledger-fcc1e.temp_ryan.edc_grading_training`
# '''

# raw = client.query(query).result().to_dataframe()
# raw.to_pickle('data/raw_data.pkl')

In [7]:
import pandas as pd

raw = pd.read_pickle('data/raw_data.pkl')
raw.head()

,phone_number_clean,interested_to_EDC_flag,ms_area,acquisition_channel,user_age,kyc_tier,loyalty_tier,age_on_core_days,age_on_ncore_days,age_on_accounting_days,...,LM3_qris_tpv,LQ1_core_count,LQ1_ppob_count,LQ1_qris_count,LQ2_core_count,LQ2_ppob_count,LQ2_qris_count,LQ3_core_count,LQ3_ppob_count,LQ3_qris_count
0,85156161281,0,JAVA 3,Organic Acquisition,<NA>,ADVANCED,Bronze,<NA>,<NA>,1013,...,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,82385749266,0,SUMATERA 2,Organic Acquisition,<NA>,ADVANCED,Bronze,<NA>,<NA>,387,...,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,85255266430,0,SULAWESI,Organic Acquisition,41,None,None,<NA>,<NA>,918,...,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,85659063508,0,JAVA 1,Organic Acquisition,<NA>,ADVANCED,Bronze,<NA>,<NA>,1054,...,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,82199060692,0,SULAWESI,Organic Acquisition,27,None,None,<NA>,<NA>,1131,...,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [8]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8055 entries, 0 to 8054
Data columns (total 59 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   phone_number_clean         8055 non-null   object
 1   interested_to_EDC_flag     8055 non-null   object
 2   ms_area                    7420 non-null   object
 3   acquisition_channel        8004 non-null   object
 4   user_age                   4380 non-null   Int64
 5   kyc_tier                   3590 non-null   object
 6   loyalty_tier               4322 non-null   object
 7   age_on_core_days           2052 non-null   Int64
 8   age_on_ncore_days          804 non-null    Int64
 9   age_on_accounting_days     7174 non-null   Int64
 10  referee_count              8055 non-null   Int64
 11  est_daily_customer         416 non-null    object
 12  count_trf                  554 non-null    object
 13  edc_count                  422 non-null    object
 14  edc_type                   423 non-null    object
 15  business_age               425 non-null    object
 16  core_before_shutdown_flag  8055 non-null   Int64
 17  ppob_before_shutdown_flag  8055 non-null   Int64
 18  m0_transaxi_cnt            6863 non-null   Int64
 19  m0_Utang_cnt               6863 non-null   Int64
 20  lm_transaxi_cnt            6863 non-null   Int64
 21  lm_Utang_cnt               6863 non-null   Int64
 22  m2_transaxi_cnt            6863 non-null   Int64
 23  m2_Utang_cnt               6863 non-null   Int64
 24  m3_transaxi_cnt            6863 non-null   Int64
 25  m3_Utang_cnt               6863 non-null   Int64
 26  LM0_core_count             3252 non-null   Int64
 27  LM0_ppob_count             3252 non-null   Int64
 28  LM0_qris_count             3252 non-null   Int64
 29  LM0_core_tpv               1000 non-null   object
 30  LM0_ppob_tpv               1250 non-null   object
 31  LM0_qris_tpv               65 non-null     object
 32  LM1_core_count             3252 non-null   Int64
 33  LM1_ppob_count             3252 non-null   Int64
 34  LM1_qris_count             3252 non-null   Int64
 35  LM1_core_tpv               1168 non-null   object
 36  LM1_ppob_tpv               1487 non-null   object
 37  LM1_qris_tpv               96 non-null     object
 38  LM2_core_count             3252 non-null   Int64
 39  LM2_ppob_count             3252 non-null   Int64
 40  LM2_qris_count             3252 non-null   Int64
 41  LM2_core_tpv               1354 non-null   object
 42  LM2_ppob_tpv               1643 non-null   object
 43  LM2_qris_tpv               194 non-null    object
 44  LM3_core_count             3252 non-null   Int64
 45  LM3_ppob_count             3252 non-null   Int64
 46  LM3_qris_count             3252 non-null   Int64
 47  LM3_core_tpv               1294 non-null   object
 48  LM3_ppob_tpv               1469 non-null   object
 49  LM3_qris_tpv               201 non-null    object
 50  LQ1_core_count             3252 non-null   Int64
 51  LQ1_ppob_count             3252 non-null   Int64
 52  LQ1_qris_count             3252 non-null   Int64
 53  LQ2_core_count             3252 non-null   Int64
 54  LQ2_ppob_count             3252 non-null   Int64
 55  LQ2_qris_count             3252 non-null   Int64
 56  LQ3_core_count             3252 non-null   Int64
 57  LQ3_ppob_count             3252 non-null   Int64
 58  LQ3_qris_count             3252 non-null   Int64
dtypes: Int64(36), object(23)
memory usage: 3.9+ MB

In [9]:
# -- data cleaning
import numpy as np

lq = [col for col in raw.columns if col.startswith('LQ')]
# acc = [col for col in raw.columns if col.endswith('cnt')]

# clean some columns
df =\
(
    raw
    .assign(
        # is_ppob_flag = lambda x: np.where(pd.isnull(x.L3M_core_count), 0, 1).astype(bool),
        # is_core_q0 = lambda x: np.where(pd.isnull(x.LQ0_core_count), 0, 1).astype(bool),
        is_core_q1 = lambda x: np.where(pd.isnull(x.LQ1_core_count), 0, 1).astype(bool),
        is_core_q2 = lambda x: np.where(pd.isnull(x.LQ2_core_count), 0, 1).astype(bool),
        is_core_q3 = lambda x: np.where(pd.isnull(x.LQ3_core_count), 0, 1).astype(bool),
        # is_ppob_q0 = lambda x: np.where(pd.isnull(x.LQ0_ppob_count), 0, 1).astype(bool),
        is_ppob_q1 = lambda x: np.where(pd.isnull(x.LQ1_ppob_count), 0, 1).astype(bool),
        is_ppob_q2 = lambda x: np.where(pd.isnull(x.LQ2_ppob_count), 0, 1).astype(bool),
        is_ppob_q3 = lambda x: np.where(pd.isnull(x.LQ3_ppob_count), 0, 1).astype(bool),
        # is_qris_q0 = lambda x: np.where(pd.isnull(x.LQ0_qris_count), 0, 1).astype(bool),
        is_qris_q1 = lambda x: np.where(pd.isnull(x.LQ1_qris_count), 0, 1).astype(bool),
        is_qris_q2 = lambda x: np.where(pd.isnull(x.LQ2_qris_count), 0, 1).astype(bool),
        is_qris_q3 = lambda x: np.where(pd.isnull(x.LQ3_qris_count), 0, 1).astype(bool),
        # is_done_payment_flag = lambda x: np.where(pd.isnull(x.L3M_core_count), 0, 1).astype(bool),
        interested_to_EDC_flag = lambda x: (pd.to_numeric(x.interested_to_EDC_flag)).astype(bool),
        est_daily_customer = lambda x: pd.to_numeric(x.est_daily_customer),
        count_trf = lambda x: pd.to_numeric(x.count_trf),
        edc_count = lambda x: x.edc_count.str.replace('-','to'),
        edc_type = lambda x: x.edc_type.fillna('Empty').str.split(','),
        acquisition_channel = lambda x: x.acquisition_channel.str.replace(' Acquisition',''),
        business_age = lambda x: x.business_age.str.replace('-','to').str.split(',').str[0],
        core_before_shutdown_flag = lambda x: x.core_before_shutdown_flag.astype(bool),
        ppob_before_shutdown_flag = lambda x: x.ppob_before_shutdown_flag.astype(bool),
        kyc_tier = lambda x: x.kyc_tier.fillna('NONKYC'),
        loyalty_tier = lambda x: x.loyalty_tier.fillna('Bronze'),
        age_on_core_days = lambda x: x.age_on_core_days.fillna(0),
        age_on_ncore_days = lambda x: x.age_on_ncore_days.fillna(0),
        # age_on_accounting_days = lambda x: x.age_on_accounting_days.fillna(0)
    )
    .drop(columns=['user_age', 'referee_count', *lq])
)

# change the TPV features to numeric
tpv_col = df.filter(regex='TPV|tpv').columns
for i in tpv_col:
    df[i] = pd.to_numeric(df[i])

# normalize the numeric columns
num_col = [col for col in df.select_dtypes(include=['float', 'int']).columns if '_flag' not in col]
num_col = [col for col in df[num_col].columns if 'age' not in col]
for i in num_col:
    df[i] = df[i].fillna(0).apply(np.log1p)

# one-hot encode the edc_type columns
for i in sorted(set(sum(df['edc_type'].tolist(),[]))):  
    df[f'edc_type_{i}'] = (df['edc_type'].apply(lambda x: x.count(i) if i in x else None)).fillna(0).astype(bool)

# one-hot encode other columns
df = pd.get_dummies(data=df, columns=['ms_area', 'acquisition_channel', 'kyc_tier', 'loyalty_tier', 'edc_count', 'business_age'], prefix=['ms', 'acq', 'kyc', 'lyl', 'edc_count', 'bizage'], dtype=bool)

# drop some columns
df = df.drop(columns=['edc_type_Empty', 'edc_type', 'ms_#N/A', 'kyc_NONKYC'])

# four = [col for col in df.columns if '4' in col]
# five = [col for col in df.columns if '5' in col]
# overall = [col for col in df.columns if 'overall' in col]
# thismo1 = [col for col in df.columns if 'm0' in col]
# thismo2 = [col for col in df.columns if 'M0' in col]
# lastmonth1 = [col for col in df.columns if 'lm' in col]
# lastmonth2 = [col for col in df.columns if 'LM' in col]
# ms = [col for col in df.columns if 'ms' in col]
# days = [col for col in df.columns if 'days' in col]

# df = df.drop(columns=[*four, *five, *overall])
# df = df.drop(columns=[*days])

# save the cleaned data
df.to_pickle('data/cleaned_data.pkl')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8055 entries, 0 to 8054
Data columns (total 86 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   phone_number_clean         8055 non-null   object
 1   interested_to_EDC_flag     8055 non-null   bool
 2   age_on_core_days           8055 non-null   Int64
 3   age_on_ncore_days          8055 non-null   Int64
 4   age_on_accounting_days     7174 non-null   Int64
 5   est_daily_customer         8055 non-null   float64
 6   count_trf                  8055 non-null   float64
 7   core_before_shutdown_flag  8055 non-null   bool
 8   ppob_before_shutdown_flag  8055 non-null   bool
 9   m0_transaxi_cnt            8055 non-null   Float64
 10  m0_Utang_cnt               8055 non-null   Float64
 11  lm_transaxi_cnt            8055 non-null   Float64
 12  lm_Utang_cnt               8055 non-null   Float64
 13  m2_transaxi_cnt            8055 non-null   Float64
 14  m2_Utang_cnt               8055 non-null   Float64
 15  m3_transaxi_cnt            8055 non-null   Float64
 16  m3_Utang_cnt               8055 non-null   Float64
 17  LM0_core_count             8055 non-null   Float64
 18  LM0_ppob_count             8055 non-null   Float64
 19  LM0_qris_count             8055 non-null   Float64
 20  LM0_core_tpv               8055 non-null   float64
 21  LM0_ppob_tpv               8055 non-null   float64
 22  LM0_qris_tpv               8055 non-null   float64
 23  LM1_core_count             8055 non-null   Float64
 24  LM1_ppob_count             8055 non-null   Float64
 25  LM1_qris_count             8055 non-null   Float64
 26  LM1_core_tpv               8055 non-null   float64
 27  LM1_ppob_tpv               8055 non-null   float64
 28  LM1_qris_tpv               8055 non-null   float64
 29  LM2_core_count             8055 non-null   Float64
 30  LM2_ppob_count             8055 non-null   Float64
 31  LM2_qris_count             8055 non-null   Float64
 32  LM2_core_tpv               8055 non-null   float64
 33  LM2_ppob_tpv               8055 non-null   float64
 34  LM2_qris_tpv               8055 non-null   float64
 35  LM3_core_count             8055 non-null   Float64
 36  LM3_ppob_count             8055 non-null   Float64
 37  LM3_qris_count             8055 non-null   Float64
 38  LM3_core_tpv               8055 non-null   float64
 39  LM3_ppob_tpv               8055 non-null   float64
 40  LM3_qris_tpv               8055 non-null   float64
 41  is_core_q1                 8055 non-null   bool
 42  is_core_q2                 8055 non-null   bool
 43  is_core_q3                 8055 non-null   bool
 44  is_ppob_q1                 8055 non-null   bool
 45  is_ppob_q2                 8055 non-null   bool
 46  is_ppob_q3                 8055 non-null   bool
 47  is_qris_q1                 8055 non-null   bool
 48  is_qris_q2                 8055 non-null   bool
 49  is_qris_q3                 8055 non-null   bool
 50  edc_type_BCA               8055 non-null   bool
 51  edc_type_BNII              8055 non-null   bool
 52  edc_type_BRI               8055 non-null   bool
 53  edc_type_BSI               8055 non-null   bool
 54  edc_type_Mandiri           8055 non-null   bool
 55  edc_type_Others            8055 non-null   bool
 56  ms_BALI NUSRA              8055 non-null   bool
 57  ms_JAKARTA                 8055 non-null   bool
 58  ms_JAVA 1                  8055 non-null   bool
 59  ms_JAVA 2                  8055 non-null   bool
 60  ms_JAVA 3                  8055 non-null   bool
 61  ms_KALIMANTAN              8055 non-null   bool
 62  ms_SULAWESI                8055 non-null   bool
 63  ms_SUMATERA 1              8055 non-null   bool
 64  ms_SUMATERA 2              8055 non-null   bool
 65  ms_SUMATERA 3              8055 non-null   bool
 66  acq_Offline                8055 non-null   bool
 67  acq_Organic                8055 non-null   bool
 68  acq_Paid                   8055 non-null   bool
 69  acq_Referral               8055 non-null   bool
 70  kyc_ADVANCED               8055 non-null   bool
 71  kyc_SUPREME                8055 non-null   bool
 72  lyl_Bronze                 8055 non-null   bool
 73  lyl_Diamond                8055 non-null   bool
 74  lyl_Gold                   8055 non-null   bool
 75  lyl_Platinum               8055 non-null   bool
 76  lyl_Silver                 8055 non-null   bool
 77  edc_count_0                8055 non-null   bool
 78  edc_count_1                8055 non-null   bool
 79  edc_count_2to3             8055 non-null   bool
 80  edc_count_3to6             8055 non-null   bool
 81  edc_count_>10              8055 non-null   bool
 82  bizage_0to1                8055 non-null   bool
 83  bizage_1to3                8055 non-null   bool
 84  bizage_3to5                8055 non-null   bool
 85  bizage_5+                  8055 non-null   bool
dtypes: Float64(20), Int64(3), bool(48), float64(14), object(1)
memory usage: 2.9+ MB